#!/bin/bash
# Ping the IP address 5 times

# Check the number of arguments
if [ $# -eq 0 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    # Ping the value 5 times
    ping -c 5 "$1"
fi
